### ISSUE TITLE
Decide f-droid update "style"

### ISSUE THREAD

**Issue by ironjan** [Codingspezis/metal-only#80]
According to [Inclusion How-To](https://f-droid.org/wiki/page/Inclusion_How-To#Updating), f-droid supports the following update mechanisms:

 * **tag checking:** faster updates, more "beta-like" (tagging does not necessarily imply "productive google play release")
 * **checking Google Play**: slower but more stable.

My recommendation: tag checking.

**Comment by ironjan** [comment]
May I assume that releases are tagged? If so, we could close this issue and submit the app to f-droid (#81).

**Comment by rbrtslmn** [comment]
Sorry - Yes, independence from Google Play is a good idea in my opinion.
