### ISSUE TITLE
Submit metal-only to f-droid

### ISSUE THREAD

**Issue by ironjan** [Codingspezis/metal-only#81]
Submission data according to [Inclusion_How-To](https://f-droid.org/wiki/page/Inclusion_How-To):

**Source Code:** https://github.com/Codingspezis/metal-only/
**License:** Apache License, Version 2.0
**Issue Tracker:** https://github.com/Codingspezis/metal-only/issues/
**Donations:** http://www.metal-only.de/?action=donation (Donations are not sent to the devs but to the internet radio "metal only")

**Usability:** Does not require root, no tracking

**Summary:** Companion app to the internet radio station of http://metal-only.de 

**Description:** Metal Only is a German internet radio station playing all variants of rock and metal. This is the official "companion app" which has some station specific feature like 
 * Showing the station's show plan
 * Enabling the user to submit song wishes and greetings
 * Add calendar entries for your favorite shows
 * Share your favorite shows with your friends

Note: currently most parts of the app are in German because Metal Only is a German internet radio station. Translation to English is in progress though.

**Updating:** Via tagging of releases. Pattern: v$major.$minor.$patch(prerelease?)
prerelease may be (alpha|beta)$count

**Potential Anti-Feature:** Depends on the internet stream of http://metal-only.de - Metal Only charitable, non-profit NGO. The server stream is probably running on proprietary software; the streams are in non-free formats (mp3, acc).

----

Submission to f-droid via [submission queue](https://f-droid.org/forums/forum/submission-queue/).

**Comment by rbrtslmn** [comment]
Updated license.

**Comment by ironjan** [comment]
Submitted: https://f-droid.org/forums/topic/metal-only/
