### ISSUE TITLE
Request: Play Button on Pull Down Menu

### ISSUE THREAD

**Issue by scorcher24** [Codingspezis/metal-only#95]
Would be nice to have a play/pause button on the android pull down menu available, so you can pause/play there directly without going into the app. I hope you know what I mean, it's the menu you can pull down by swiping down from the top of the screen while any app or no app is running in the foreground. An entry is already there, I think it should be possible to add a button for that, like Google Music has.

**Comment by ironjan** [comment]
Thanks for the suggestion. This is already planned (#39) but it's unknown when this can be implemented. Feel free to submit a pull request if you're able to implement this ;)
